### ISSUE TITLE
ST-013 remove delay after clicking the start button

### ISSUE THREAD

**Issue by haubitzer** [sw21-tug/Team_15#30]
**Describe the bug**
There is a delay between clicking the start button and the first update of the timer clock. Maybe 1 second.

**Expected behavior**
There should be instant feedback after the click. 
There are two possible ways:
* have the timer clock disabled (grey font color) when no timer is running
* start with 00:00:01 when the user clicks the button

**Comment by kereczt** [comment]
we opted for a third option:
initially display "-- : -- : --" as defalut string intead of "00:00:00" 
for later starts it doesn't matter as there will already be the last time displayed beforehand and then reset to "00:00:00"

we also decreased the interval in which the timer is updated before it could happen, that the update of the timer was slightly delayed
